"""
集計キーのカテゴリ分類定義（完全版）。
CrossFactor風のカテゴリ + 日本語ラベル。18カテゴリ・200+ファクター。
"""

FACTOR_CATEGORIES: dict = {
    "レース基本条件": {
        "icon": "🏇",
        "factors": [
            {"key": "jrd_bac.keibajo_code",         "label": "競馬場",            "desc": "01札幌〜10小倉"},
            {"key": "jrd_bac.kyori",                 "label": "距離",              "desc": "メートル"},
            {"key": "jrd_bac.track_code",            "label": "トラック種別",      "desc": "芝/ダート/障害"},
            {"key": "jrd_bac.kyoso_shubetsu_code",   "label": "競走種別",          "desc": "平地/障害"},
            {"key": "jrd_bac.kyoso_joken_code",      "label": "競走条件",          "desc": "新馬/未勝利/1勝等"},
            {"key": "jrd_bac.kyoso_kigo_code",       "label": "競走記号",          "desc": ""},
            {"key": "jrd_bac.juryo_shubetsu_code",   "label": "重量種別",          "desc": "馬齢/定量/別定/ハンデ"},
            {"key": "jrd_bac.grade_code",            "label": "グレード",          "desc": "G1/G2/G3/OP/L"},
            {"key": "jrd_bac.course_kubun",          "label": "コース区分",        "desc": "A/B/C/D"},
            {"key": "jrd_bac.kaisai_kubun",          "label": "開催区分",          "desc": ""},
            {"key": "jrd_bac.toroku_tosu",           "label": "登録頭数",          "desc": ""},
        ],
    },
    "天候・馬場": {
        "icon": "🌤",
        "factors": [
            {"key": "jrd_kab.tenko_code",               "label": "天候",                  "desc": "晴/曇/雨/小雨/雪"},
            {"key": "jrd_kab.babajotai_code_shiba",     "label": "馬場状態（芝）",        "desc": "良/稍重/重/不良"},
            {"key": "jrd_kab.babajotai_code_dirt",      "label": "馬場状態（ダート）",    "desc": "良/稍重/重/不良"},
            {"key": "jrd_kab.babajotai_shiba_uchi",     "label": "芝内側状態",            "desc": ""},
            {"key": "jrd_kab.babajotai_shiba_naka",     "label": "芝中間状態",            "desc": ""},
            {"key": "jrd_kab.babajotai_shiba_soto",     "label": "芝外側状態",            "desc": ""},
            {"key": "jrd_kab.babasa_shiba",             "label": "芝馬場差",              "desc": ""},
            {"key": "jrd_kab.babajotai_dirt_uchi",      "label": "ダート内側状態",        "desc": ""},
            {"key": "jrd_kab.babajotai_dirt_naka",      "label": "ダート中間状態",        "desc": ""},
            {"key": "jrd_kab.babajotai_dirt_soto",      "label": "ダート外側状態",        "desc": ""},
            {"key": "jrd_kab.babasa_dirt",              "label": "ダート馬場差",          "desc": ""},
            {"key": "jrd_kab.renzoku_nannichime",       "label": "連続何日目",            "desc": ""},
            {"key": "jrd_kab.shiba_shurui",             "label": "芝種類",                "desc": ""},
            {"key": "jrd_kab.chukan_kosuiryo",          "label": "中間降水量",            "desc": ""},
        ],
    },
    "JRDB指数（前日）": {
        "icon": "📊",
        "factors": [
            {"key": "jrd_kyi.idm",              "label": "IDM（総合指数）",   "desc": "JRDB独自の総合能力値"},
            {"key": "jrd_kyi.sogo_shisu",       "label": "総合指数",          "desc": ""},
            {"key": "jrd_kyi.kishu_shisu",      "label": "騎手指数",          "desc": ""},
            {"key": "jrd_kyi.joho_shisu",       "label": "情報指数",          "desc": ""},
            {"key": "jrd_kyi.chokyo_shisu",     "label": "調教指数",          "desc": ""},
            {"key": "jrd_kyi.kyusha_shisu",     "label": "厩舎指数",          "desc": ""},
            {"key": "jrd_kyi.ninki_shisu",      "label": "人気指数",          "desc": ""},
            {"key": "jrd_kyi.ten_shisu",        "label": "テン指数",          "desc": "スタートダッシュ力"},
            {"key": "jrd_kyi.pace_shisu",       "label": "ペース指数",        "desc": ""},
            {"key": "jrd_kyi.agari_shisu",      "label": "上がり指数",        "desc": "終盤の脚力"},
            {"key": "jrd_kyi.ichi_shisu",       "label": "位置指数",          "desc": ""},
            {"key": "jrd_kyi.gekiso_shisu",     "label": "激走指数",          "desc": "穴馬検出用"},
            {"key": "jrd_kyi.manken_shisu",     "label": "万券指数",          "desc": ""},
            {"key": "jrd_kyi.uma_start_shisu",  "label": "スタート指数",      "desc": ""},
        ],
    },
    "JRDB指数順位": {
        "icon": "🔢",
        "factors": [
            {"key": "jrd_kyi.gekiso_juni",      "label": "激走順位",          "desc": ""},
            {"key": "jrd_kyi.ls_shisu_juni",    "label": "LS指数順位",        "desc": ""},
            {"key": "jrd_kyi.ten_shisu_juni",   "label": "テン指数順位",      "desc": ""},
            {"key": "jrd_kyi.pace_shisu_juni",  "label": "ペース指数順位",    "desc": ""},
            {"key": "jrd_kyi.agari_shisu_juni", "label": "上がり指数順位",    "desc": ""},
            {"key": "jrd_kyi.ichi_shisu_juni",  "label": "位置指数順位",      "desc": ""},
        ],
    },
    "馬基本情報": {
        "icon": "🐴",
        "factors": [
            {"key": "jvd_se.barei",                     "label": "馬齢",                  "desc": "2歳〜"},
            {"key": "jvd_se.seibetsu_code",             "label": "性別",                  "desc": "牡/牝/セン"},
            {"key": "jvd_se.futan_juryo",               "label": "斤量",                  "desc": "負担重量kg"},
            {"key": "jvd_se.bataiju",                   "label": "馬体重",                "desc": "kg"},
            {"key": "jvd_se.zogen_sa",                  "label": "馬体重増減",            "desc": "前走比kg"},
            {"key": "jvd_se.wakuban",                   "label": "枠番",                  "desc": "1〜8"},
            {"key": "jvd_se.umaban",                    "label": "馬番",                  "desc": "1〜18"},
            {"key": "jrd_kyi.kyakushitsu_code",         "label": "脚質コード",            "desc": "逃/先/差/追"},
            {"key": "jrd_kyi.kyori_tekisei_code",       "label": "距離適性",              "desc": ""},
            {"key": "jrd_kyi.kyori_tekisei_code_2",     "label": "距離適性2",             "desc": ""},
            {"key": "jrd_kyi.class_code",               "label": "クラスコード",          "desc": ""},
            {"key": "jrd_kyi.joshodo_code",             "label": "上昇度コード",          "desc": ""},
            {"key": "jrd_kyi.joken_class_code",         "label": "条件クラスコード",      "desc": ""},
            {"key": "jrd_kyi.rotation",                 "label": "ローテーション",        "desc": "前走からの間隔"},
            {"key": "jrd_kyi.seibetsu_code",            "label": "性別（JRDB）",          "desc": ""},
            {"key": "jrd_kyi.blinker_shiyo_kubun",      "label": "ブリンカー",            "desc": "0=なし/1=あり"},
            {"key": "jrd_kyi.umakigo_code",             "label": "馬記号コード",          "desc": ""},
            {"key": "jrd_kyi.torikeshi_flag",           "label": "取消フラグ",            "desc": ""},
            {"key": "jrd_kyi.kokyu_flag",               "label": "呼吸フラグ",            "desc": ""},
            {"key": "jrd_kyi.gekiso_type",              "label": "激走タイプ",            "desc": ""},
            {"key": "jrd_kyi.kyuyo_riyu_bunrui_code",   "label": "休養理由分類",          "desc": ""},
            {"key": "jrd_kyi.nyukyu_nansome",           "label": "入厩何走目",            "desc": ""},
            {"key": "jrd_kyi.nyukyu_nannichimae",       "label": "入厩何日前",            "desc": ""},
        ],
    },
    "オッズ・人気": {
        "icon": "💰",
        "factors": [
            {"key": "jvd_se.tansho_odds",               "label": "単勝オッズ（確定）",        "desc": ""},
            {"key": "jvd_se.tansho_ninkijun",           "label": "単勝人気順",                "desc": ""},
            {"key": "jrd_kyi.kijun_odds_tansho",        "label": "基準オッズ（単勝）",        "desc": "前日オッズ"},
            {"key": "jrd_kyi.kijun_odds_fukusho",       "label": "基準オッズ（複勝）",        "desc": "前日オッズ"},
            {"key": "jrd_kyi.kijun_ninkijun_tansho",    "label": "基準人気順（単勝）",        "desc": ""},
            {"key": "jrd_kyi.kijun_ninkijun_fukusho",   "label": "基準人気順（複勝）",        "desc": ""},
        ],
    },
    "騎手・調教師": {
        "icon": "👤",
        "factors": [
            {"key": "jrd_kyi.kishu_code",                   "label": "騎手コード",            "desc": ""},
            {"key": "jrd_kyi.kishumei",                     "label": "騎手名",                "desc": ""},
            {"key": "jrd_kyi.chokyoshi_code",               "label": "調教師コード",          "desc": ""},
            {"key": "jrd_kyi.chokyoshimei",                 "label": "調教師名",              "desc": ""},
            {"key": "jrd_kyi.chokyoshi_shozoku",            "label": "調教師所属",            "desc": "美浦/栗東"},
            {"key": "jrd_kyi.kishu_minarai_code",           "label": "騎手見習い",            "desc": "減量"},
            {"key": "jrd_kyi.kishu_kitai_rentai_ritsu",     "label": "騎手期待連対率",        "desc": ""},
            {"key": "jrd_kyi.kishu_kitai_tansho_ritsu",     "label": "騎手期待単勝率",        "desc": ""},
            {"key": "jrd_kyi.kishu_kitai_sanchakunai_ritsu","label": "騎手期待3着内率",       "desc": ""},
            {"key": "jrd_kyi.kyusha_rank",                  "label": "厩舎ランク",            "desc": ""},
            {"key": "jrd_kyi.hobokusaki",                   "label": "放牧先",                "desc": ""},
            {"key": "jrd_kyi.hobokusaki_rank",              "label": "放牧先ランク",          "desc": ""},
            {"key": "jrd_kyi.banushimei",                   "label": "馬主名",                "desc": ""},
            {"key": "jrd_kyi.banushikai_code",              "label": "馬主会コード",          "desc": ""},
        ],
    },
    "適性": {
        "icon": "🎯",
        "factors": [
            {"key": "jrd_kyi.tekisei_code_shiba",   "label": "芝適性",        "desc": "◎/○/△"},
            {"key": "jrd_kyi.tekisei_code_dirt",    "label": "ダート適性",    "desc": "◎/○/△"},
            {"key": "jrd_kyi.tekisei_code_omo",     "label": "重馬場適性",    "desc": "◎/○/△"},
            {"key": "jrd_kyi.soho",                 "label": "走法",          "desc": ""},
            {"key": "jrd_kyi.taikei",               "label": "体型",          "desc": ""},
            {"key": "jrd_kyi.taikei_sogo_1",        "label": "体型総合1",     "desc": ""},
            {"key": "jrd_kyi.taikei_sogo_2",        "label": "体型総合2",     "desc": ""},
            {"key": "jrd_kyi.taikei_sogo_3",        "label": "体型総合3",     "desc": ""},
            {"key": "jrd_kyi.uma_tokki_1",          "label": "馬特記1",       "desc": ""},
            {"key": "jrd_kyi.uma_tokki_2",          "label": "馬特記2",       "desc": ""},
            {"key": "jrd_kyi.uma_tokki_3",          "label": "馬特記3",       "desc": ""},
            {"key": "jrd_kyi.uma_deokure_ritsu",    "label": "出遅れ率",      "desc": ""},
        ],
    },
    "蹄・馬具・馬体": {
        "icon": "🦶",
        "factors": [
            {"key": "jrd_kyi.hizume_code",      "label": "蹄コード",          "desc": ""},
            {"key": "jrd_skb.tokki_code",       "label": "特記コード",        "desc": ""},
            {"key": "jrd_skb.bagu_code",        "label": "馬具コード",        "desc": ""},
            {"key": "jrd_skb.sogo",             "label": "総合評価（馬体）",  "desc": ""},
            {"key": "jrd_skb.hidarimae",        "label": "左前",              "desc": "蹄"},
            {"key": "jrd_skb.migimae",          "label": "右前",              "desc": "蹄"},
            {"key": "jrd_skb.hidariushiro",     "label": "左後",              "desc": "蹄"},
            {"key": "jrd_skb.migiushiro",       "label": "右後",              "desc": "蹄"},
            {"key": "jrd_skb.hami",             "label": "ハミ",              "desc": "馬具"},
            {"key": "jrd_skb.bandage",          "label": "バンテージ",        "desc": "馬具"},
            {"key": "jrd_skb.teitetsu",         "label": "蹄鉄",              "desc": ""},
            {"key": "jrd_skb.hizume_jotai",     "label": "蹄状態",            "desc": ""},
            {"key": "jrd_skb.soe",              "label": "ソエ",              "desc": ""},
            {"key": "jrd_skb.kotsuryu",         "label": "骨瘤",              "desc": ""},
        ],
    },
    "調教データ": {
        "icon": "🏋",
        "factors": [
            {"key": "jrd_kyi.chokyo_yajirushi_code",    "label": "調教矢印",              "desc": "↑↗→↘↓"},
            {"key": "jrd_kyi.kyusha_hyoka_code",        "label": "厩舎評価",              "desc": ""},
            {"key": "jrd_cyb.chokyo_type",              "label": "調教タイプ",            "desc": ""},
            {"key": "jrd_cyb.chokyo_corse_shubetsu",    "label": "調教コース種別",        "desc": ""},
            {"key": "jrd_cyb.oikiri_shisu",             "label": "追切指数",              "desc": ""},
            {"key": "jrd_cyb.shiage_shisu",             "label": "仕上指数",              "desc": ""},
            {"key": "jrd_cyb.chokyo_ryo_hyoka",         "label": "調教量評価",            "desc": ""},
            {"key": "jrd_cyb.shiage_shisu_henka",       "label": "仕上指数変化",          "desc": ""},
            {"key": "jrd_cyb.chokyo_hyoka",             "label": "調教評価",              "desc": ""},
            {"key": "jrd_cyb.oikiri_shisu_isshumae",    "label": "追切指数（1週前）",     "desc": ""},
            {"key": "jrd_cha.oikiri_shurui",            "label": "追切種類",              "desc": ""},
            {"key": "jrd_cha.oikiri_shisu",             "label": "追切指数（調教）",      "desc": ""},
            {"key": "jrd_cha.chokyo_f",                 "label": "調教F",                 "desc": ""},
            {"key": "jrd_cha.shimai_f",                 "label": "終いF",                 "desc": ""},
            {"key": "jrd_cha.ten_f",                    "label": "テンF",                 "desc": ""},
        ],
    },
    "展開予想": {
        "icon": "📈",
        "factors": [
            {"key": "jrd_kyi.pace_yoso",        "label": "ペース予想",        "desc": "S/M/H"},
            {"key": "jrd_kyi.dochu_juni",       "label": "道中順位",          "desc": "予想"},
            {"key": "jrd_kyi.dochu_sa",         "label": "道中差",            "desc": ""},
            {"key": "jrd_kyi.dochu_uchisoto",   "label": "道中内外",          "desc": ""},
            {"key": "jrd_kyi.kohan_3f_juni",    "label": "後半3F順位",        "desc": "予想"},
            {"key": "jrd_kyi.kohan_3f_sa",      "label": "後半3F差",          "desc": ""},
            {"key": "jrd_kyi.kohan_3f_uchisoto","label": "後半3F内外",        "desc": ""},
            {"key": "jrd_kyi.goal_juni",        "label": "ゴール順位",        "desc": "予想"},
            {"key": "jrd_kyi.goal_sa",          "label": "ゴール差",          "desc": ""},
            {"key": "jrd_kyi.goal_uchisoto",    "label": "ゴール内外",        "desc": ""},
            {"key": "jrd_kyi.tenkai_kigo_code", "label": "展開記号",          "desc": ""},
        ],
    },
    "印・マーク": {
        "icon": "✏",
        "factors": [
            {"key": "jrd_kyi.shirushi_code_1",  "label": "印1（総合）",   "desc": ""},
            {"key": "jrd_kyi.shirushi_code_2",  "label": "印2（IDM）",    "desc": ""},
            {"key": "jrd_kyi.shirushi_code_3",  "label": "印3（情報）",   "desc": ""},
            {"key": "jrd_kyi.shirushi_code_4",  "label": "印4",           "desc": ""},
            {"key": "jrd_kyi.shirushi_code_5",  "label": "印5",           "desc": ""},
            {"key": "jrd_kyi.manken_shirushi",  "label": "万券印",        "desc": ""},
        ],
    },
    "特定情報・総合情報": {
        "icon": "📝",
        "factors": [
            {"key": "jrd_kyi.tokutei_joho_1",   "label": "特定情報1",     "desc": ""},
            {"key": "jrd_kyi.tokutei_joho_2",   "label": "特定情報2",     "desc": ""},
            {"key": "jrd_kyi.tokutei_joho_3",   "label": "特定情報3",     "desc": ""},
            {"key": "jrd_kyi.tokutei_joho_4",   "label": "特定情報4",     "desc": ""},
            {"key": "jrd_kyi.tokutei_joho_5",   "label": "特定情報5",     "desc": ""},
            {"key": "jrd_kyi.sogo_joho_1",      "label": "総合情報1",     "desc": ""},
            {"key": "jrd_kyi.sogo_joho_2",      "label": "総合情報2",     "desc": ""},
            {"key": "jrd_kyi.sogo_joho_3",      "label": "総合情報3",     "desc": ""},
            {"key": "jrd_kyi.sogo_joho_4",      "label": "総合情報4",     "desc": ""},
            {"key": "jrd_kyi.sogo_joho_5",      "label": "総合情報5",     "desc": ""},
            {"key": "jrd_kyi.flag",             "label": "フラグ",        "desc": ""},
        ],
    },
    "直前情報（当日）": {
        "icon": "⏰",
        "factors": [
            {"key": "jrd_tyb.idm",                      "label": "IDM（直前）",           "desc": "当日更新値"},
            {"key": "jrd_tyb.kishu_shisu",              "label": "騎手指数（直前）",      "desc": ""},
            {"key": "jrd_tyb.joho_shisu",               "label": "情報指数（直前）",      "desc": ""},
            {"key": "jrd_tyb.odds_shisu",               "label": "オッズ指数",            "desc": ""},
            {"key": "jrd_tyb.paddock_shisu",            "label": "パドック指数",          "desc": ""},
            {"key": "jrd_tyb.sogo_shisu",               "label": "総合指数（直前）",      "desc": ""},
            {"key": "jrd_tyb.batai_code",               "label": "馬体コード",            "desc": ""},
            {"key": "jrd_tyb.kehai_code",               "label": "気配コード",            "desc": ""},
            {"key": "jrd_tyb.tansho_odds",              "label": "単勝オッズ（直前）",    "desc": ""},
            {"key": "jrd_tyb.odds_fukusho",             "label": "複勝オッズ（直前）",    "desc": ""},
            {"key": "jrd_tyb.bataiju",                  "label": "馬体重（直前）",        "desc": ""},
            {"key": "jrd_tyb.bataiju_zogen",            "label": "馬体重増減（直前）",    "desc": ""},
            {"key": "jrd_tyb.babajotai_code",           "label": "馬場状態（直前）",      "desc": ""},
            {"key": "jrd_tyb.tenko_code",               "label": "天候（直前）",          "desc": ""},
            {"key": "jrd_tyb.odds_shirushi",            "label": "オッズ印",              "desc": ""},
            {"key": "jrd_tyb.paddock_shirushi",         "label": "パドック印",            "desc": ""},
            {"key": "jrd_tyb.chokuzen_sogo_shirushi",   "label": "直前総合印",            "desc": ""},
        ],
    },
    "CID・LS・BB指数": {
        "icon": "🔬",
        "factors": [
            {"key": "jrd_joa.cid_soten",            "label": "CID素点",               "desc": ""},
            {"key": "jrd_joa.cid_chokyo_soten",     "label": "CID調教素点",           "desc": ""},
            {"key": "jrd_joa.cid_kyusha_soten",     "label": "CID厩舎素点",           "desc": ""},
            {"key": "jrd_joa.cid",                  "label": "CID",                   "desc": ""},
            {"key": "jrd_joa.ls_shisu",             "label": "LS指数",                "desc": ""},
            {"key": "jrd_joa.ls_hyoka",             "label": "LS評価",                "desc": ""},
            {"key": "jrd_joa.em",                   "label": "EM",                    "desc": ""},
            {"key": "jrd_joa.kyusha_bb_shirushi",   "label": "厩舎BB印",              "desc": ""},
            {"key": "jrd_joa.kishu_bb_shirushi",    "label": "騎手BB印",              "desc": ""},
            {"key": "jrd_joa.kijun_odds_tansho",    "label": "基準オッズ単勝（JOA）", "desc": ""},
            {"key": "jrd_joa.kijun_odds_fukusho",   "label": "基準オッズ複勝（JOA）", "desc": ""},
        ],
    },
    "成績データ（確定）": {
        "icon": "🏆",
        "factors": [
            {"key": "jrd_sed.kakutei_chakujun",         "label": "確定着順",                  "desc": ""},
            {"key": "jrd_sed.ijo_kubun_code",           "label": "異常区分",                  "desc": "0=正常"},
            {"key": "jrd_sed.soha_time",                "label": "走破タイム",                "desc": "0.1秒"},
            {"key": "jrd_sed.futan_juryo",              "label": "斤量（確定）",              "desc": ""},
            {"key": "jrd_sed.tansho_odds",              "label": "単勝オッズ（確定SED）",     "desc": ""},
            {"key": "jrd_sed.tansho_ninkijun",          "label": "単勝人気順（確定SED）",     "desc": ""},
            {"key": "jrd_sed.idm",                      "label": "IDM（確定）",               "desc": ""},
            {"key": "jrd_sed.soten",                    "label": "素点",                      "desc": ""},
            {"key": "jrd_sed.babasa",                   "label": "馬場差",                    "desc": ""},
            {"key": "jrd_sed.pace",                     "label": "ペース",                    "desc": ""},
            {"key": "jrd_sed.deokure",                  "label": "出遅れ",                    "desc": ""},
            {"key": "jrd_sed.ichidori",                 "label": "位置取り",                  "desc": ""},
            {"key": "jrd_sed.furi",                     "label": "不利",                      "desc": ""},
            {"key": "jrd_sed.ten_shisu",                "label": "テン指数（確定）",          "desc": ""},
            {"key": "jrd_sed.agari_shisu",              "label": "上がり指数（確定）",        "desc": ""},
            {"key": "jrd_sed.pace_shisu",               "label": "ペース指数（確定）",        "desc": ""},
            {"key": "jrd_sed.race_p_shisu",             "label": "レースP指数",               "desc": ""},
            {"key": "jrd_sed.race_pace",                "label": "レースペース",              "desc": ""},
            {"key": "jrd_sed.uma_pace",                 "label": "馬ペース",                  "desc": ""},
            {"key": "jrd_sed.kyakushitsu_code",         "label": "脚質（確定）",              "desc": ""},
            {"key": "jrd_sed.course_dori_code",         "label": "コース取り",                "desc": ""},
            {"key": "jrd_sed.joshodo_code",             "label": "上昇度（確定）",            "desc": ""},
            {"key": "jrd_sed.class_code",               "label": "クラス（確定）",            "desc": ""},
            {"key": "jrd_sed.batai_code",               "label": "馬体コード（確定）",        "desc": ""},
            {"key": "jrd_sed.kehai_code",               "label": "気配コード（確定）",        "desc": ""},
            {"key": "jrd_sed.odds_fukusho",             "label": "複勝オッズ（確定SED）",     "desc": ""},
            {"key": "jrd_sed.corner_1",                 "label": "コーナー1位置",             "desc": ""},
            {"key": "jrd_sed.corner_2",                 "label": "コーナー2位置",             "desc": ""},
            {"key": "jrd_sed.corner_3",                 "label": "コーナー3位置",             "desc": ""},
            {"key": "jrd_sed.corner_4",                 "label": "コーナー4位置",             "desc": ""},
            {"key": "jrd_sed.haraimodoshi_tansho",      "label": "払戻金（単勝）",            "desc": ""},
            {"key": "jrd_sed.haraimodoshi_fukusho",     "label": "払戻金（複勝）",            "desc": ""},
            {"key": "jrd_sed.bataiju",                  "label": "馬体重（確定）",            "desc": ""},
            {"key": "jrd_sed.bataiju_zogen",            "label": "馬体重増減（確定）",        "desc": ""},
            {"key": "jrd_sed.kohan_3f",                 "label": "後半3F",                    "desc": ""},
            {"key": "jrd_sed.zenhan_3f_taimu",          "label": "前半3F",                    "desc": ""},
        ],
    },
    "血統": {
        "icon": "🧬",
        "factors": [
            {"key": "jrd_ukc.bamei_chichi",             "label": "父馬名",            "desc": ""},
            {"key": "jrd_ukc.bamei_haha",               "label": "母馬名",            "desc": ""},
            {"key": "jrd_ukc.bamei_hahachichi",         "label": "母父馬名",          "desc": "BMS"},
            {"key": "jrd_ukc.keito_code_chichi",        "label": "父系統コード",      "desc": ""},
            {"key": "jrd_ukc.keito_code_hahachichi",    "label": "母父系統コード",    "desc": ""},
            {"key": "jrd_ukc.seibetsu_code",            "label": "性別（馬情報）",    "desc": ""},
            {"key": "jrd_ukc.moshoku_code",             "label": "毛色コード",        "desc": ""},
        ],
    },
    "過去成績参照": {
        "icon": "📋",
        "factors": [
            {"key": "jrd_kka.jra",                  "label": "JRA成績",               "desc": ""},
            {"key": "jrd_kka.koryu",                "label": "交流成績",              "desc": ""},
            {"key": "jrd_kka.shiba_dirt",           "label": "芝ダート成績",          "desc": ""},
            {"key": "jrd_kka.shiba_dirt_kyori",     "label": "芝ダート距離別",        "desc": ""},
            {"key": "jrd_kka.torakku_kyori",        "label": "トラック距離別",        "desc": ""},
            {"key": "jrd_kka.rotation",             "label": "ローテーション",        "desc": ""},
            {"key": "jrd_kka.mawari",               "label": "回り別成績",            "desc": "右/左"},
            {"key": "jrd_kka.kishu",                "label": "騎手別成績",            "desc": ""},
            {"key": "jrd_kka.ryo",                  "label": "良馬場成績",            "desc": ""},
            {"key": "jrd_kka.yayaomo",              "label": "稍重成績",              "desc": ""},
            {"key": "jrd_kka.omo",                  "label": "重馬場成績",            "desc": ""},
            {"key": "jrd_kka.pace_s",               "label": "Sペース成績",           "desc": ""},
            {"key": "jrd_kka.pace_m",               "label": "Mペース成績",           "desc": ""},
            {"key": "jrd_kka.pace_h",               "label": "Hペース成績",           "desc": ""},
            {"key": "jrd_kka.kisetsu",              "label": "季節別成績",            "desc": ""},
            {"key": "jrd_kka.waku",                 "label": "枠番別成績",            "desc": ""},
            {"key": "jrd_kka.kishu_kyori",          "label": "騎手距離別",            "desc": ""},
            {"key": "jrd_kka.kishu_track",          "label": "騎手トラック別",        "desc": ""},
            {"key": "jrd_kka.kishu_chokyoshi",      "label": "騎手調教師別",          "desc": ""},
            {"key": "jrd_kka.kishu_banushi",        "label": "騎手馬主別",            "desc": ""},
            {"key": "jrd_kka.kishu_blinker",        "label": "騎手ブリンカー別",      "desc": ""},
            {"key": "jrd_kka.chokyoshi_banushi",    "label": "調教師馬主別",          "desc": ""},
        ],
    },
    "JRA-VAN成績": {
        "icon": "📦",
        "factors": [
            {"key": "jvd_se.ijo_kubun_code",        "label": "異常区分（JRA-VAN）",       "desc": ""},
            {"key": "jvd_se.kakutei_chakujun",      "label": "確定着順（JRA-VAN）",       "desc": ""},
            {"key": "jvd_se.soha_time",             "label": "走破タイム（JRA-VAN）",     "desc": ""},
            {"key": "jvd_se.corner_1",              "label": "コーナー1（JRA-VAN）",      "desc": ""},
            {"key": "jvd_se.corner_2",              "label": "コーナー2（JRA-VAN）",      "desc": ""},
            {"key": "jvd_se.corner_3",              "label": "コーナー3（JRA-VAN）",      "desc": ""},
            {"key": "jvd_se.corner_4",              "label": "コーナー4（JRA-VAN）",      "desc": ""},
            {"key": "jvd_se.kohan_4f",              "label": "後半4F（JRA-VAN）",         "desc": ""},
            {"key": "jvd_se.kohan_3f",              "label": "後半3F（JRA-VAN）",         "desc": ""},
            {"key": "jvd_se.time_sa",               "label": "タイム差（JRA-VAN）",       "desc": ""},
            {"key": "jvd_se.kyakushitsu_hantei",    "label": "脚質判定（JRA-VAN）",       "desc": ""},
        ],
    },
}
