"""
集計キーのカテゴリ分類定義。
CrossFactor風のカテゴリ + 日本語ラベル。
"""

FACTOR_CATEGORIES: dict = {
    "レース条件": {
        "icon": "🏇",
        "factors": [
            {"key": "jrd_bac.keibajo_code",        "label": "競馬場コード",          "desc": "01=札幌〜10=小倉"},
            {"key": "jrd_bac.kyori",                "label": "距離",                  "desc": "1000〜3600m"},
            {"key": "jrd_bac.track_code",           "label": "トラックコード",        "desc": "芝/ダート/障害"},
            {"key": "jrd_bac.kyoso_joken_code",     "label": "競走条件コード",        "desc": "新馬/未勝利/1勝クラス等"},
            {"key": "jrd_bac.grade_code",           "label": "グレード",              "desc": "G1/G2/G3/OP/L"},
            {"key": "jrd_bac.kyoso_shubetsu_code",  "label": "競走種別",              "desc": "平地/障害"},
            {"key": "jrd_bac.juryo_shubetsu_code",  "label": "重量種別",              "desc": "馬齢/定量/別定/ハンデ"},
            {"key": "jrd_bac.course_kubun",         "label": "コース区分",            "desc": "A/B/C/D"},
            {"key": "jrd_kab.tenko_code",           "label": "天候",                  "desc": "晴/曇/雨/小雨/雪/小雪"},
            {"key": "jrd_kab.babajotai_code_shiba", "label": "馬場状態（芝）",       "desc": "良/稍重/重/不良"},
            {"key": "jrd_kab.babajotai_code_dirt",  "label": "馬場状態（ダート）",   "desc": "良/稍重/重/不良"},
        ],
    },
    "JRDB指数": {
        "icon": "📊",
        "factors": [
            {"key": "jrd_kyi.idm",              "label": "IDM（総合指数）",   "desc": "JRDB独自の総合能力指数"},
            {"key": "jrd_kyi.sogo_shisu",       "label": "総合指数",          "desc": ""},
            {"key": "jrd_kyi.kishu_shisu",      "label": "騎手指数",          "desc": ""},
            {"key": "jrd_kyi.joho_shisu",       "label": "情報指数",          "desc": ""},
            {"key": "jrd_kyi.chokyo_shisu",     "label": "調教指数",          "desc": ""},
            {"key": "jrd_kyi.kyusha_shisu",     "label": "厩舎指数",          "desc": ""},
            {"key": "jrd_kyi.ten_shisu",        "label": "テン指数",          "desc": "スタートダッシュ力"},
            {"key": "jrd_kyi.pace_shisu",       "label": "ペース指数",        "desc": ""},
            {"key": "jrd_kyi.agari_shisu",      "label": "上がり指数",        "desc": "終盤の脚力"},
            {"key": "jrd_kyi.ichi_shisu",       "label": "位置指数",          "desc": ""},
            {"key": "jrd_kyi.ninki_shisu",      "label": "人気指数",          "desc": ""},
            {"key": "jrd_kyi.gekiso_shisu",     "label": "激走指数",          "desc": "穴馬検出用"},
            {"key": "jrd_kyi.manken_shisu",     "label": "万券指数",          "desc": ""},
        ],
    },
    "馬基本情報": {
        "icon": "🐴",
        "factors": [
            {"key": "jvd_se.barei",                     "label": "馬齢",              "desc": "2歳〜"},
            {"key": "jvd_se.seibetsu_code",             "label": "性別",              "desc": "牡/牝/セン"},
            {"key": "jvd_se.futan_juryo",               "label": "斤量",              "desc": "負担重量(kg)"},
            {"key": "jvd_se.bataiju",                   "label": "馬体重",            "desc": "kg"},
            {"key": "jvd_se.zogen_sa",                  "label": "馬体重増減",        "desc": "前走比kg"},
            {"key": "jrd_kyi.blinker_shiyo_kubun",      "label": "ブリンカー",        "desc": "0=なし/1=あり"},
            {"key": "jrd_kyi.kyakushitsu_code",         "label": "脚質コード",        "desc": "逃/先/差/追"},
            {"key": "jrd_kyi.kyori_tekisei_code",       "label": "距離適性",          "desc": ""},
            {"key": "jrd_kyi.class_code",               "label": "クラスコード",      "desc": ""},
            {"key": "jrd_kyi.joshodo_code",             "label": "上昇度コード",      "desc": ""},
        ],
    },
    "オッズ・人気": {
        "icon": "💰",
        "factors": [
            {"key": "jvd_se.tansho_odds",               "label": "単勝オッズ（確定）",    "desc": ""},
            {"key": "jvd_se.tansho_ninkijun",           "label": "単勝人気順",            "desc": ""},
            {"key": "jrd_kyi.kijun_odds_tansho",        "label": "基準オッズ（単勝）",    "desc": "JRDB前日オッズ"},
            {"key": "jrd_kyi.kijun_odds_fukusho",       "label": "基準オッズ（複勝）",    "desc": "JRDB前日オッズ"},
            {"key": "jrd_kyi.kijun_ninkijun_tansho",    "label": "基準人気順（単勝）",    "desc": ""},
        ],
    },
    "騎手・調教師": {
        "icon": "👤",
        "factors": [
            {"key": "jrd_kyi.kishu_code",               "label": "騎手コード",            "desc": ""},
            {"key": "jrd_kyi.chokyoshi_code",           "label": "調教師コード",          "desc": ""},
            {"key": "jrd_kyi.kishu_minarai_code",       "label": "騎手見習いコード",      "desc": ""},
            {"key": "jrd_kyi.chokyoshi_shozoku",        "label": "調教師所属",            "desc": "美浦/栗東"},
            {"key": "jrd_kyi.kyusha_rank",              "label": "厩舎ランク",            "desc": ""},
            {"key": "jrd_kyi.kishu_kitai_rentai_ritsu", "label": "騎手期待連対率",        "desc": ""},
            {"key": "jrd_kyi.hobokusaki_rank",          "label": "放牧先ランク",          "desc": ""},
        ],
    },
    "適性コード": {
        "icon": "🎯",
        "factors": [
            {"key": "jrd_kyi.tekisei_code_shiba",   "label": "芝適性",        "desc": "◎/○/△"},
            {"key": "jrd_kyi.tekisei_code_dirt",    "label": "ダート適性",    "desc": "◎/○/△"},
            {"key": "jrd_kyi.tekisei_code_omo",     "label": "重馬場適性",    "desc": "◎/○/△"},
            {"key": "jrd_kyi.kyori_tekisei_code_2", "label": "距離適性2",     "desc": ""},
            {"key": "jrd_kyi.soho",                 "label": "走法",          "desc": ""},
            {"key": "jrd_kyi.taikei",               "label": "体型",          "desc": ""},
        ],
    },
    "調教データ": {
        "icon": "🏋️",
        "factors": [
            {"key": "jrd_kyi.chokyo_yajirushi_code",    "label": "調教矢印コード",    "desc": "↑↗→↘↓"},
            {"key": "jrd_kyi.kyusha_hyoka_code",        "label": "厩舎評価コード",    "desc": ""},
            {"key": "jrd_cyb.chokyo_type",              "label": "調教タイプ",        "desc": ""},
            {"key": "jrd_cyb.oikiri_shisu",             "label": "追切指数",          "desc": ""},
            {"key": "jrd_cyb.shiage_shisu",             "label": "仕上指数",          "desc": ""},
            {"key": "jrd_cyb.chokyo_ryo_hyoka",         "label": "調教量評価",        "desc": ""},
            {"key": "jrd_cyb.chokyo_hyoka",             "label": "調教評価",          "desc": ""},
        ],
    },
    "展開予想": {
        "icon": "📈",
        "factors": [
            {"key": "jrd_kyi.pace_yoso",        "label": "ペース予想",        "desc": "S/M/H"},
            {"key": "jrd_kyi.dochu_juni",       "label": "道中順位",          "desc": "予想"},
            {"key": "jrd_kyi.dochu_sa",         "label": "道中差",            "desc": ""},
            {"key": "jrd_kyi.dochu_uchisoto",   "label": "道中内外",          "desc": ""},
            {"key": "jrd_kyi.kohan_3f_juni",    "label": "後半3F順位",        "desc": "予想"},
            {"key": "jrd_kyi.goal_juni",        "label": "ゴール順位",        "desc": "予想"},
            {"key": "jrd_kyi.tenkai_kigo_code", "label": "展開記号コード",    "desc": ""},
        ],
    },
    "成績データ（確定）": {
        "icon": "🏆",
        "factors": [
            {"key": "jrd_sed.kakutei_chakujun",     "label": "確定着順",              "desc": ""},
            {"key": "jrd_sed.soha_time",            "label": "走破タイム",            "desc": "0.1秒単位"},
            {"key": "jrd_sed.idm",                  "label": "IDM（確定）",           "desc": "レース後確定値"},
            {"key": "jrd_sed.soten",                "label": "素点",                  "desc": ""},
            {"key": "jrd_sed.babasa",               "label": "馬場差",                "desc": ""},
            {"key": "jrd_sed.pace",                 "label": "ペース",                "desc": ""},
            {"key": "jrd_sed.ten_shisu",            "label": "テン指数（確定）",      "desc": ""},
            {"key": "jrd_sed.agari_shisu",          "label": "上がり指数（確定）",    "desc": ""},
            {"key": "jrd_sed.pace_shisu",           "label": "ペース指数（確定）",    "desc": ""},
            {"key": "jrd_sed.kyakushitsu_code",     "label": "脚質（確定）",          "desc": "実際の脚質"},
            {"key": "jrd_sed.course_dori_code",     "label": "コース取り",            "desc": ""},
            {"key": "jrd_sed.joshodo_code",         "label": "上昇度コード（確定）",  "desc": ""},
            {"key": "jrd_sed.class_code",           "label": "クラスコード（確定）",  "desc": ""},
        ],
    },
    "血統": {
        "icon": "🧬",
        "factors": [
            {"key": "jrd_ukc.bamei_chichi",         "label": "父馬名",            "desc": ""},
            {"key": "jrd_ukc.bamei_haha",           "label": "母馬名",            "desc": ""},
            {"key": "jrd_ukc.bamei_hahachichi",     "label": "母父馬名",          "desc": "BMS"},
            {"key": "jrd_ukc.keito_code_chichi",    "label": "父系統コード",      "desc": ""},
            {"key": "jrd_ukc.keito_code_hahachichi","label": "母父系統コード",    "desc": ""},
        ],
    },
    "直前情報": {
        "icon": "⏰",
        "factors": [
            {"key": "jrd_tyb.idm",          "label": "IDM（直前）",           "desc": "当日更新値"},
            {"key": "jrd_tyb.sogo_shisu",   "label": "総合指数（直前）",      "desc": ""},
            {"key": "jrd_tyb.paddock_shisu","label": "パドック指数",           "desc": ""},
            {"key": "jrd_tyb.odds_shisu",   "label": "オッズ指数",            "desc": ""},
            {"key": "jrd_tyb.batai_code",   "label": "馬体コード",            "desc": ""},
            {"key": "jrd_tyb.kehai_code",   "label": "気配コード",            "desc": ""},
            {"key": "jrd_tyb.tansho_odds",  "label": "単勝オッズ（直前）",   "desc": ""},
        ],
    },
    "CID・LS指数": {
        "icon": "🔢",
        "factors": [
            {"key": "jrd_joa.cid_soten",    "label": "CID素点",   "desc": ""},
            {"key": "jrd_joa.cid",          "label": "CID",       "desc": ""},
            {"key": "jrd_joa.ls_shisu",     "label": "LS指数",    "desc": ""},
            {"key": "jrd_joa.ls_hyoka",     "label": "LS評価",    "desc": ""},
            {"key": "jrd_joa.em",           "label": "EM",        "desc": ""},
        ],
    },
    "過去成績参照": {
        "icon": "📋",
        "factors": [
            {"key": "jrd_kka.shiba_dirt",           "label": "芝ダート成績",          "desc": ""},
            {"key": "jrd_kka.shiba_dirt_kyori",     "label": "芝ダート距離別成績",    "desc": ""},
            {"key": "jrd_kka.kishu",                "label": "騎手別成績",            "desc": ""},
            {"key": "jrd_kka.rotation",             "label": "ローテーション",        "desc": ""},
            {"key": "jrd_kka.pace_s",               "label": "Sペース成績",           "desc": ""},
            {"key": "jrd_kka.pace_m",               "label": "Mペース成績",           "desc": ""},
            {"key": "jrd_kka.pace_h",               "label": "Hペース成績",           "desc": ""},
            {"key": "jrd_kka.kisetsu",              "label": "季節別成績",            "desc": ""},
            {"key": "jrd_kka.waku",                 "label": "枠番別成績",            "desc": ""},
        ],
    },
}
